//
// Created by her on 18/06/15.
//

#ifndef MORTALKOMBAT_TALLER1C2015_BEINGPUSHED_H
#define MORTALKOMBAT_TALLER1C2015_BEINGPUSHED_H


class BeingPushed {

};


#endif //MORTALKOMBAT_TALLER1C2015_BEINGPUSHED_H
