#ifndef MORTALKOMBAT_TALLER1C2015_MOVERIGHT_H
#define MORTALKOMBAT_TALLER1C2015_MOVERIGHT_H


#include "MKEvent.h"

class MoveRight : public MKEvent {

};


#endif //MORTALKOMBAT_TALLER1C2015_MOVERIGHT_H
