//
// Created by mauri on 29/05/15.
//

#ifndef MORTALKOMBAT_TALLER1C2015_MKSTAGACONTROLLER_H
#define MORTALKOMBAT_TALLER1C2015_MKSTAGACONTROLLER_H


class MKStagaController {
    virtual void update() = 0;
};


#endif //MORTALKOMBAT_TALLER1C2015_MKSTAGACONTROLLER_H
